RUNNER=distribute
FRAMEWORK=testng
MAX_RETRY_COUNT=2
CAPS=./caps/notepad/notepad_windows_capabilities.json
RUNNER_LEVEL=methods
WEB_ENGINE=selenium
APP_NAME=Notepad
APP_PACKAGE_NAME=Notepad
ENVIRONMENT_CONFIG_FILE=./src/test/resources/environments.json
LOG_DIR=target
LOG_PROPERTIES_FILE=./src/test/resources/log4j2.properties
PARALLEL=1
PLATFORM=windows
RUN_IN_CI=false
TARGET_ENVIRONMENT=local
TEST_DATA_FILE=./src/test/resources/testData.json
BROWSER_CONFIG_FILE=./configs/browser_config.json
SHOW_SENSITIVE_DATA=false
